app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import UserRegisterView


urlpatterns = [
    path('register/',UserRegisterView.as_view(), name='register'),
   
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from typing import Any
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from PIL import Image

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ("first_name", "last_name","username", "email", "password", "password2",)
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("A user with this email address already exists.")
        return email

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "email",)
        
        
class ProfileUpdateForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)
    
    image = forms.ImageField(label="Image",widget=forms.FileInput(), required=False,error_messages={"invalid":("image files only")})
    
    class Meta:
        model = Profile
        fields =("bio","date_of_birth","image",)
        
    def save(self,*args,**kwargs):
        img = super().save(*args,**kwargs)
        
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('x')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        
        if x and y and w and h:
            image = Image.open(img.image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((300,300),Image.ANTIALIAS)
            resized_image.save(img.image.path)
            
        return img

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.css" integrity="sha512-iAcZ4OrGhQ7KDqtM+LMc+iuv63aJ9O7hPyWBzCXsrZYuhJ6jhdeh40+hf9o4QmZVu8QrH/cWy/JTmoKNOL4Urw==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Word-Bucket | {% block title %}{% endblock %}</title>
</head>
<body>
    <header class="site-header">

        <!-- NAVBAR -->
        {% include 'blog/navbar.html' %}
    </header>

    <!-- MAIN SECTION -->
    <main role="main" class="container">
      <div class="row">

          <!-- MESSAGES -->
          <div class="col-md-8 m-auto">
            {% if messages %}
              {% for message in messages %}
                <div class="alert {{ message.tags }}">
                  {{message}}
                </div>
              {% endfor %}
            {% endif %}           
          </div>

          
          {% block content %}{% endblock %}
          

      </div>
    </main>

    <!-- SCRIPTS -->
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js" integrity="sha512-E+gDQcIvNXE60SjCS38ysf1mGh4ObBpKcUOp0oEaHQHQAdaN2p7GelOpgEdpTuCLoIJyLkNXiqFZbyD9Ak/Ygw==" crossorigin="anonymous"></script>
      
      <script>
        $(function () {
    
          /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
          $("#id_image").change(function () {
            if (this.files && this.files[0]) {
              var reader = new FileReader();
              reader.onload = function (e) {
                $("#image").attr("src", e.target.result);
                $("#modalCrop").modal('show');
              }
              reader.readAsDataURL(this.files[0]);
            }
          });
    
          /* SCRIPTS TO HANDLE THE CROPPER BOX */
          var $image = $("#image");
          var cropBoxData;
          var canvasData;
          $("#modalCrop").on("shown.bs.modal", function () {
            $image.cropper({
              viewMode: 1,
              aspectRatio: 1/1,
              minCropBoxWidth: 200,
              minCropBoxHeight: 200,
              ready: function () {
                $image.cropper("setCanvasData", canvasData);
                $image.cropper("setCropBoxData", cropBoxData);
              }
            });
          }).on("hidden.bs.modal", function () {
            cropBoxData = $image.cropper("getCropBoxData");
            canvasData = $image.cropper("getCanvasData");
            $image.cropper("destroy");
            location.reload();
          });
    
          $(".js-zoom-in").click(function () {
            $image.cropper("zoom", 0.1);
          });
    
          $(".js-zoom-out").click(function () {
            $image.cropper("zoom", -0.1);
          });
    
          /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
          $(".js-crop-and-upload").click(function () {
            var cropData = $image.cropper("getData");
            // console.log(cropData);
            $("#id_x").val(cropData["x"]);
            $("#id_y").val(cropData["y"]);
            $("#id_height").val(cropData["height"]);
            $("#id_width").val(cropData["width"]);
            $("#formUpload").submit();
          });
    
        });
      </script>

      <script type="text/javascript">

        $(document).ready(function(event){
          
          // $("#chat-box").scrollTop($("#chat-box")[0].scrollHeight);

          // LIKE POSTS

          $(document).on('click','#like',function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
              type: 'POST',
              url: '{% url "post-like" %}',
              data: {'id':pk, 'csrfmiddlewaretoken':'{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  $('#like-section').html(response['form']);
                  console.log($('#like-section').html(response['form']));
              },
              error: function(rs, e){
                  console.log(rs.responseText);
              },
            });
          });

          // COMMENT LIKE

          $(document).on('click','.clike',function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
              type: 'POST',
              url: "{% url 'comment-like' %}",
              data: {'id':pk, 'pid':'{{post.pk}}', 'csrfmiddlewaretoken':'{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  $('.main-comment-section').html(response['form']);
                  console.log($('.main-comment-section').html(response['form']));
              },
              error: function(rs, e){
                  console.log(rs.responseText);
              },
            });
          });

          // SAVE POSTS

          $(document).on('click','#save',function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
              type: 'POST',
              url: '{% url "post-save" %}',
              data: {'id':pk, 'csrfmiddlewaretoken':'{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  $('#save-section').html(response['form']);
                  console.log($('#save-section').html(response['form']));
              },
              error: function(rs, e){
                  console.log(rs.responseText);
              },
            });
          });

          // COMMENT FORM

          $(document).on('submit','.comment-form', function(event){
            event.preventDefault();
            console.log($(this).serialize());
            $.ajax({
              type: 'POST',
              url: $(this).attr('action'),
              data: $(this).serialize(),
              dataType: 'json',
              success: function(response){
                $('.main-comment-section').html(response['form']);
                console.log(response['form'])
                $('textarea').val('');
              },
              error: function(rs, e){
                console.log(rs.responseText);
              },
            });
          });

          // REPLY FORM

          $(document).on('submit','.reply-form', function(event){
            event.preventDefault();
            console.log($(this).serialize());
            $.ajax({
              type: 'POST',
              url: $(this).attr('action'),
              data: $(this).serialize(),
              dataType: 'json',
              success: function(response){
                $('.main-comment-section').html(response['form']);
                console.log(response['form'])
                $('textarea').val('');
              },
              error: function(rs, e){
                console.log(rs.responseText);
              },
            });
          });

        });


      </script>

      {% block script %}{% endblock %}

</body>
</html>